language: php

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

dist: bionic
sudo: required

matrix:
  fast_finish: true
  include:
    # Test the latest stable release
    - php: 7.2
    - php: 7.2
      env: PREFER_LOWEST="--prefer-lowest"
    - php: 7.4

before_script:
- composer update --prefer-dist $PREFER_LOWEST
script:
- "./vendor/bin/phpunit"
after_script:
- if [ -z "$PREFER_LOWEST" ]; then ./vendor/bin/coveralls -v; fi
