language: php
php:
- 7.2
cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty
sudo: required

env:
  matrix:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""
before_script:
- composer update --prefer-dist $PREFER_LOWEST
script:
- "./vendor/bin/phpunit"
after_script:
- if [ -z "$PREFER_LOWEST" ]; then ./vendor/bin/coveralls -v; fi
